void tela4() {
  int minuto;
  int segundo;
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(BLACK);
  display.setCursor(64,0); 
  display.println(salto);
  display.setCursor(0,0);
  display.print("RT: ");
  minuto=rt/60;
  segundo=rt;
  display.print((minuto / 10)% 6);
  display.print(minuto % 10);
  display.print(":");
  display.print((segundo / 10)% 6);
  display.println(segundo % 10);
  display.print("SH: ");
  display.println(sh);
  display.print("FFT: ");
  minuto=fft/60;
  segundo=fft;
  display.print((minuto / 10)% 6);
  display.print(minuto % 10);
  display.print(":");
  display.print((segundo / 10)% 6);
  display.println(segundo % 10);
  display.print("DH: ");
  display.println(dh);
  display.print("NAVT: ");  
  minuto=navt/60;
  segundo=navt;
  display.print((minuto / 10)% 6);
  display.print(minuto % 10);
  display.print(":");
  display.print((segundo / 10)% 6);
  display.println(segundo % 10);
  display.display();
  delay(150);
}
